[file]
traffic = ./data/METR-LA/flow_metrla.npz
meta = ./data/METR-LA/metrla_meta.csv
adj = ./data/METR-LA/adj.npy
model = ./cpt/metrla_idea1_ultra
log = ./log/metrla_log

[data]
input_len = 12
output_len = 12
train_ratio = 0.7
val_ratio = 0.1
test_ratio = 0.2

[train]
cuda = 0
max_epoch = 100
batch_size = 64
learning_rate = 0.001
weight_decay = 0.0001
seed = 1

[param]
factors = 1
layers = 3
tps = 12
tpn = 1
recur = 5
sps = 9
spn = 32
nodes = 207
tod = 288  
dow = 7
id = 1
nd = 64
td = 32
dd = 32