[file]
traffic = ./data/PEMS03/PEMS03.npz
adj = ./data/PEMS03/adj.pkl
meta = ./data/PEMS03/meta_pems03.csv
model = ./cpt/pems03_freqcot_best
log = ./log/pems03_log

[data]
input_len = 12
output_len = 12
train_ratio = 0.6
val_ratio = 0.2
test_ratio = 0.2

[train]
cuda = 0
max_epoch = 150
batch_size = 64
learning_rate = 0.001
weight_decay = 0.0001
seed = 1

[param]
nodes = 358
factors = 1
layers = 3
tps = 12
tpn = 1
recur = 5
sps = 12
spn = 32
tod = 288  
dow = 7
id = 1
nd = 64
td = 32
dd = 32