[file]
traffic = ./data/PEMS08/PEMS08.npz
meta = ./data/PEMS08/meta_pems08.csv
adj = ./data/PEMS08/adj.pkl
model = ./cpt/pems08_freqcot
log = ./log/pems08_log

[data]
input_len = 12
output_len = 12
train_ratio = 0.6
val_ratio = 0.2
test_ratio = 0.2

[train]
cuda = 0
max_epoch = 150
batch_size = 64
learning_rate = 0.0005
weight_decay = 0.001
seed = 1

[param]
nodes = 170
factors = 1
layers = 3
tps = 12
tpn = 1
recur = 5
sps = 17
spn = 32
tod = 288  
dow = 7
id = 1
nd = 64
td = 32
dd = 32